# ═══════════════════════════════════════════════════════════════════════════
# WHERE THINGS LIVE -- one definition, sourced by every notebook and script.
#
#   cohorts/            COMMITTED and persisting. The frozen splits, the cohort
#                       assignment, and the clinical trait list. Nothing here is
#                       regenerated by a run; deleting it loses the split.
#   proteins/           COMMITTED. Curated prior knowledge -- gene sets that the
#                       analysis is interpreted against, not derived from.
#   data/               GITIGNORED. The Zenodo download.
#   data/run_artifacts/ GITIGNORED. Everything a run can regenerate: .rds, the
#                       derived .csv tables, the figures. Safe to delete.
#   src/                R that is not a notebook.
#   ipynb/              notebooks, and nothing else.
#
# The root is found by walking up for the environment file, so this works
# whether you are in ipynb/, in src/, or at the repository root:
#
#   source("../src/paths.R")     # from a notebook
#   source("src/paths.R")        # from the root
# ═══════════════════════════════════════════════════════════════════════════

.find_root <- function(start = getwd()) {
  d <- normalizePath(start, mustWork = TRUE)
  repeat {
    if (file.exists(file.path(d, "endotypes-proteomics.yml"))) return(d)
    up <- dirname(d)
    if (identical(up, d))
      stop("endotypes-proteomics.yml not found above '", start,
           "' -- are you inside the repository?", call. = FALSE)
    d <- up
  }
}

ROOT      <- .find_root()
RAW       <- file.path(ROOT, "data", "SLE_doi.10.5281_zenodo_20342569")
COHORTS   <- file.path(ROOT, "cohorts")
PROTEINS  <- file.path(ROOT, "proteins")
ARTIFACTS <- file.path(ROOT, "data", "run_artifacts")

dir.create(ARTIFACTS, showWarnings = FALSE, recursive = TRUE)

raw <- function(fmt, ...) file.path(RAW,       sprintf(fmt, ...))
coh <- function(fmt, ...) file.path(COHORTS,   sprintf(fmt, ...))
art <- function(fmt, ...) file.path(ARTIFACTS, sprintf(fmt, ...))
pro <- function(fmt, ...) file.path(PROTEINS,  sprintf(fmt, ...))

# ── the two committed metadata files ──────────────────────────────────────

# The 15 clinical traits, with the antigen-system groups that must be held out
# together. Anti-Sm correlates +0.52 with anti-RNP-A in cohort A and anti-Ro52
# correlates +0.73 with anti-Ro60, so dropping one member of a group leaks
# through the others.
read_traits <- function() {
  t <- read.csv(coh("clinical-traits.csv"), stringsAsFactors = FALSE)
  stopifnot(all(c("name","source_column","type","group") %in% names(t)))
  t
}

# ── the one dependency conda cannot carry ─────────────────────────────────
#
# VarSelLCM has no conda package on any platform or subdir, so it is installed
# from CRAN on demand. Steps 04 and 12 call ensure_pkg() before library().
#
# It contains C++, so it compiles. conda's R invokes a conda compiler by name
# (e.g. arm64-apple-darwin20.0.0-clang) and fails with "command not found" if
# it is absent -- which is why `compilers` is declared in the environment file.
#
# Everything else, WGCNA included, is a declared conda package. On Apple
# Silicon that requires creating the environment with CONDA_SUBDIR=osx-64,
# because bioconda has no osx-arm64 build of r-wgcna.

ensure_pkg <- function(pkg, repos = "https://cloud.r-project.org") {
  if (requireNamespace(pkg, quietly = TRUE)) return(invisible(TRUE))
  message("installing ", pkg, " from CRAN (no conda package on any platform)")
  install.packages(pkg, repos = repos)
  if (!requireNamespace(pkg, quietly = TRUE))
    stop(pkg, " is required and could not be installed.\n",
         "  It compiles, so the environment needs `compilers` -- see ",
         "endotypes-proteomics.yml", call. = FALSE)
  invisible(TRUE)
}

# ── probes vs proteins ────────────────────────────────────────────────────
#
# A SomaScan column is a PROBE (a SOMAmer), not a protein. Several probes can
# target the same protein: ISG15 has two, STAT1 has two. feature_metadata.txt
# ships GeneSymbol already disambiguated as SYMBOL_seqid, so the column name
# carries the probe identity and the gene has to be recovered by stripping it.
#
# This matters for the federation release rule. That rule is p < n, and p is a
# count of independent measurements -- two probes for ISG15 are not two
# proteins. Counting probes inflates p and makes a panel look less releasable
# than it is. Across the whole menu: 7,288 probes -> 6,399 gene symbols.

probe_to_gene <- function(columns) sub("_seq\\.[0-9.]+$", "", columns)

# Distinct proteins behind a set of probe columns. `by` is "gene" (the default,
# from the column name alone, no file read) or "uniprot" (authoritative, needs
# the study download).
n_proteins <- function(columns, by = c("gene", "uniprot")) {
  by <- match.arg(by)
  if (by == "gene") return(length(unique(probe_to_gene(columns))))
  fm <- read.delim(raw("feature_metadata.txt"), check.names = FALSE)
  length(unique(setNames(fm$UniProt, fm$GeneSymbol)[columns]))
}

# "n probes (m proteins)", for every size this pipeline prints.
size_str <- function(columns)
  sprintf("%d probes (%d proteins)", length(columns), n_proteins(columns))

# The curated interferon-stimulated gene set. Returns the panel COLUMN names,
# because feature_metadata.txt already disambiguates multi-probe genes as
# SYMBOL_seqid -- "ISG15" alone matches no column, "ISG15_seq.14148.2" does.
read_ifn_panel <- function(columns = NULL) {
  if (!requireNamespace("jsonlite", quietly = TRUE))
    stop("jsonlite is needed to read proteins/*.json -- it is in ",
         "endotypes-proteomics.yml as r-jsonlite", call. = FALSE)
  j <- jsonlite::fromJSON(pro("interferon-response-genes.json"),
                          simplifyDataFrame = FALSE)
  probes <- unlist(lapply(j$genes, function(g)
    vapply(g$somascan_probes, function(p) p$column, character(1))))
  if (is.null(columns)) return(probes)
  intersect(probes, columns)                 # only what this panel carries
}

# Which WGCNA module is the interferon module? The one the curated set lands in
# most often. This is a claim that can FAIL -- if no module holds a plurality of
# the set, there is no interferon module in this fit and the caller should be
# told, not handed a colour.
locate_ifn_module <- function(mods, columns, min_hits = 3L) {
  hits <- mods[match(read_ifn_panel(columns), columns)]
  hits <- hits[!is.na(hits) & hits != "grey"]
  if (!length(hits)) stop("no curated ISG probe landed in a named module", call. = FALSE)
  tally <- sort(table(hits), decreasing = TRUE)
  if (tally[[1]] < min_hits)
    stop(sprintf("no module holds %d or more of the curated ISG set (best: '%s' with %d) -- there is no interferon module in this fit",
                 min_hits, names(tally)[1], tally[[1]]), call. = FALSE)
  structure(names(tally)[1], hits = tally)
}

# ── showing figures in the notebook ───────────────────────────────────────
#
# Figures are written to data/run_artifacts/ as PNG. Rendered notebooks are
# committed, so each figure is also displayed as cell output. Displaying the
# file that was just written, rather than drawing a second time, means the
# notebook shows exactly what is on disk.
#
# IRdisplay only works inside a Jupyter kernel. Under Rscript this prints the
# filenames and nothing else, so run_all.sh is unaffected.

show_figures <- function(pattern) {
  fs <- sort(list.files(ARTIFACTS, pattern = pattern, full.names = TRUE))
  if (!length(fs)) { cat("no figure matches", pattern, "\n"); return(invisible(NULL)) }
  in_kernel <- isTRUE(getOption("jupyter.in_kernel"))
  for (f in fs) {
    cat(basename(f), "\n")
    if (in_kernel) IRdisplay::display_png(file = f)
  }
  if (!in_kernel) cat("(not in a Jupyter kernel, so the images are not inlined here)\n")
  invisible(fs)
}

# ── provenance ────────────────────────────────────────────────────────────
#
# Rendered notebooks are committed, so each one records where it ran. The
# package versions are the part that actually varies between a laptop and the
# ADAPTS / Lifebit platform.

run_provenance <- function() {
  si <- Sys.info()
  cat("run on   :", si[["nodename"]], "(", si[["sysname"]], si[["release"]], ")\n")
  cat("date     :", format(Sys.time(), "%Y-%m-%d %H:%M %Z"), "\n")
  cat("R        :", R.version.string, "|", R.version$platform, "\n")
  env <- Sys.getenv("CONDA_PREFIX")
  cat("R comes from:", if (nzchar(env)) env else "system R, no conda environment active", "\n")
  cat("packages :\n")
  for (p in c("WGCNA", "ComplexHeatmap", "sva", "VarSelLCM", "cluster", "fpc", "circlize")) {
    v <- tryCatch(as.character(packageVersion(p)), error = function(e) "not installed")
    cat(sprintf("   %-16s %s\n", p, v))
  }
  invisible(NULL)
}
