# ═══════════════════════════════════════════════════════════════════════════
# WHERE THINGS LIVE -- one definition, sourced by every notebook and script.
#
#   cohorts/            COMMITTED and persisting. The frozen splits, the cohort
#                       assignment, and the clinical trait list. Nothing here is
#                       regenerated by a run; deleting it loses the split.
#   proteins/           COMMITTED. Curated prior knowledge -- gene sets that the
#                       analysis is interpreted against, not derived from.
#   data/               GITIGNORED. The Zenodo download.
#   data/run_artifacts/ GITIGNORED. Everything a run can regenerate: .rds, the
#                       derived .csv tables, the figures. Safe to delete.
#   src/                R that is not a notebook.
#   ipynb/              notebooks, and nothing else.
#
# The root is found by walking up for the environment file, so this works
# whether you are in ipynb/, in src/, or at the repository root:
#
#   source("../src/paths.R")     # from a notebook
#   source("src/paths.R")        # from the root
# ═══════════════════════════════════════════════════════════════════════════

.find_root <- function(start = getwd()) {
  d <- normalizePath(start, mustWork = TRUE)
  repeat {
    if (file.exists(file.path(d, "endotypes-proteomics.yml"))) return(d)
    up <- dirname(d)
    if (identical(up, d))
      stop("endotypes-proteomics.yml not found above '", start,
           "' -- are you inside the repository?", call. = FALSE)
    d <- up
  }
}

ROOT      <- .find_root()
RAW       <- file.path(ROOT, "data", "SLE_doi.10.5281_zenodo_20342569")
COHORTS   <- file.path(ROOT, "cohorts")
PROTEINS  <- file.path(ROOT, "proteins")
ARTIFACTS <- file.path(ROOT, "data", "run_artifacts")

dir.create(ARTIFACTS, showWarnings = FALSE, recursive = TRUE)

raw <- function(fmt, ...) file.path(RAW,       sprintf(fmt, ...))
coh <- function(fmt, ...) file.path(COHORTS,   sprintf(fmt, ...))
art <- function(fmt, ...) file.path(ARTIFACTS, sprintf(fmt, ...))
pro <- function(fmt, ...) file.path(PROTEINS,  sprintf(fmt, ...))

# ── the two committed metadata files ──────────────────────────────────────

# The 15 clinical traits, with the antigen-system groups that must be held out
# together. Anti-Sm correlates +0.52 with anti-RNP-A in cohort A and anti-Ro52
# correlates +0.73 with anti-Ro60, so dropping one member of a group leaks
# through the others.
read_traits <- function() {
  t <- read.csv(coh("clinical-traits.csv"), stringsAsFactors = FALSE)
  stopifnot(all(c("name","source_column","type","group") %in% names(t)))
  t
}

# The curated interferon-stimulated gene set. Returns the panel COLUMN names,
# because feature_metadata.txt already disambiguates multi-probe genes as
# SYMBOL_seqid -- "ISG15" alone matches no column, "ISG15_seq.14148.2" does.
read_ifn_panel <- function(columns = NULL) {
  if (!requireNamespace("jsonlite", quietly = TRUE))
    stop("jsonlite is needed to read proteins/*.json -- it is in ",
         "endotypes-proteomics.yml as r-jsonlite", call. = FALSE)
  j <- jsonlite::fromJSON(pro("interferon-response-genes.json"),
                          simplifyDataFrame = FALSE)
  probes <- unlist(lapply(j$genes, function(g)
    vapply(g$somascan_probes, function(p) p$column, character(1))))
  if (is.null(columns)) return(probes)
  intersect(probes, columns)                 # only what this panel carries
}

# Which WGCNA module is the interferon module? The one the curated set lands in
# most often. This is a claim that can FAIL -- if no module holds a plurality of
# the set, there is no interferon module in this fit and the caller should be
# told, not handed a colour.
locate_ifn_module <- function(mods, columns, min_hits = 3L) {
  hits <- mods[match(read_ifn_panel(columns), columns)]
  hits <- hits[!is.na(hits) & hits != "grey"]
  if (!length(hits)) stop("no curated ISG probe landed in a named module", call. = FALSE)
  tally <- sort(table(hits), decreasing = TRUE)
  if (tally[[1]] < min_hits)
    stop(sprintf("no module holds %d or more of the curated ISG set (best: '%s' with %d) -- there is no interferon module in this fit",
                 min_hits, names(tally)[1], tally[[1]]), call. = FALSE)
  structure(names(tally)[1], hits = tally)
}
